[package]
name = "rustque"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
redis = { version = "0.24", features = ["tokio-comp", "script"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
dashmap = "5.5"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
parking_lot = "0.12"

[dev-dependencies]
tokio-test = "0.4"